# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://edison0xyz.com"

# The name of this wonderful theme ;-).
theme = 'simple-typo'

# Basic metadata configuration for your blog.
title = "/u/edison" 
author = "Edison"
copyright = "Copyright © 2025, Edison."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Theme configuration
[markup]
  [markup.highlight]
    style = 'github'
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
  # Ignore HTML warnings
  ignoreLogs = ['warning-goldmark-raw-html']

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
    
  [[menus.main]]
    name = 'Resume'
    url = '/resume'
    weight = 40

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

